****Author: Shruti<br><br>
File Name: shruti gupta- Introduction to Pandas Part 2 Assignment- week 5<br><br>
Date: 30/03/2019****

Load the ipl dataset deliveries.csv into a pandas dataframe and answer the quesions based on this dataset.

In [1]:
import pandas as pd
import numpy as np

deliveries = pd.read_csv('C:\\Users\\HP\\Documents\\Courses\\digitalvidya\\datasets\\deliveries.csv')
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,SC Ganguly,BB McCullum,P Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
1,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
3,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,4,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,5,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

#### 1. How many total extra runs have been given in the ipl matches?

In [2]:
deliveries.groupby('total_runs').extra_runs.sum()#.head()

total_runs
0       0
1    6275
2     882
3     186
4    1100
5    1036
6       0
7      40
Name: extra_runs, dtype: int64

#### 2. Which bowler bowled maximum number of overs? How many overs?

In [3]:
deliveries.bowler.value_counts()[:1]/6

Harbhajan Singh    457.0
Name: bowler, dtype: float64

#### 3. Who is the highest run scorer in this dataset? How many runs?

In [4]:
deliveries.batsman.value_counts()[:1]/6

V Kohli    539.5
Name: batsman, dtype: float64

#### 4. Return a dataframe with total runs scored by each team per match. 
##### The resulting dataframe should have 1152 rows and 4 columns and look like the df given below.

In [6]:
d = {'batting_team': {0: 'Kolkata Knight Riders',
  1: 'Royal Challengers Bangalore',
  2: 'Chennai Super Kings',
  3: 'Kings XI Punjab',
  4: 'Delhi Daredevils'},
 'bowling_team': {0: 'Royal Challengers Bangalore',
  1: 'Kolkata Knight Riders',
  2: 'Kings XI Punjab',
  3: 'Chennai Super Kings',
  4: 'Rajasthan Royals'},
 'match_id': {0: 1, 1: 1, 2: 2, 3: 2, 4: 3},
 'total_runs': {0: 222, 1: 82, 2: 240, 3: 207, 4: 132}}
df = pd.DataFrame(d)
df

,batting_team,bowling_team,match_id,total_runs
0,Kolkata Knight Riders,Royal Challengers Bangalore,1,222
1,Royal Challengers Bangalore,Kolkata Knight Riders,1,82
2,Chennai Super Kings,Kings XI Punjab,2,240
3,Kings XI Punjab,Chennai Super Kings,2,207
4,Delhi Daredevils,Rajasthan Royals,3,132

In [7]:
total_Runs = deliveries.groupby(['batting_team','bowling_team', 'match_id'],as_index = False)['total_runs'].sum()

In [8]:
total_Runs

             batting_team                 bowling_team  match_id  total_runs
0     Chennai Super Kings              Deccan Chargers        26         144
1     Chennai Super Kings              Deccan Chargers        55         148
2     Chennai Super Kings              Deccan Chargers        72         165
3     Chennai Super Kings              Deccan Chargers        85         178
4     Chennai Super Kings              Deccan Chargers       120         159
5     Chennai Super Kings              Deccan Chargers       157         138
6     Chennai Super Kings              Deccan Chargers       173         142
7     Chennai Super Kings              Deccan Chargers       213         165
8     Chennai Super Kings              Deccan Chargers       254         193
9     Chennai Super Kings              Deccan Chargers       293         160
10    Chennai Super Kings             Delhi Daredevils        20         169
11    Chennai Super Kings             Delhi Daredevils        28         188
12    Chennai Super Kings             Delhi Daredevils        66         180
13    Chennai Super Kings             Delhi Daredevils        82         163
14    Chennai Super Kings             Delhi Daredevils       126         190
15    Chennai Super Kings             Delhi Daredevils       165         112
16    Chennai Super Kings             Delhi Daredevils       230         176
17    Chennai Super Kings             Delhi Daredevils       259         110
18    Chennai Super Kings             Delhi Daredevils       305         115
19    Chennai Super Kings             Delhi Daredevils       321         222
20    Chennai Super Kings             Delhi Daredevils       345         169
21    Chennai Super Kings             Delhi Daredevils       387         168
22    Chennai Super Kings             Delhi Daredevils       406         177
23    Chennai Super Kings             Delhi Daredevils       424         181
24    Chennai Super Kings             Delhi Daredevils       460         150
25    Chennai Super Kings             Delhi Daredevils       506         119
26    Chennai Super Kings              Kings XI Punjab         2         240
27    Chennai Super Kings              Kings XI Punjab        32         181
28    Chennai Super Kings              Kings XI Punjab        57         116
29    Chennai Super Kings              Kings XI Punjab        90         185
...                   ...                          ...       ...         ...
1122  Sunrisers Hyderabad        Kolkata Knight Riders       572         149
1123  Sunrisers Hyderabad        Kolkata Knight Riders       575         162
1124  Sunrisers Hyderabad               Mumbai Indians       364         130
1125  Sunrisers Hyderabad               Mumbai Indians       385         178
1126  Sunrisers Hyderabad               Mumbai Indians       418         172
1127  Sunrisers Hyderabad               Mumbai Indians       434         157
1128  Sunrisers Hyderabad               Mumbai Indians       482         137
1129  Sunrisers Hyderabad               Mumbai Indians       513         113
1130  Sunrisers Hyderabad               Mumbai Indians       529         145
1131  Sunrisers Hyderabad               Mumbai Indians       554         177
1132  Sunrisers Hyderabad                Pune Warriors       325         126
1133  Sunrisers Hyderabad                Pune Warriors       343         119
1134  Sunrisers Hyderabad             Rajasthan Royals       357         144
1135  Sunrisers Hyderabad             Rajasthan Royals       390         136
1136  Sunrisers Hyderabad             Rajasthan Royals       396         132
1137  Sunrisers Hyderabad             Rajasthan Royals       402         133
1138  Sunrisers Hyderabad             Rajasthan Royals       428         134
1139  Sunrisers Hyderabad             Rajasthan Royals       470         127
1140  Sunrisers Hyderabad             Rajasthan Royals       499         201
1141  Sunrisers Hyderabad      Rising Pune Supergiants       539         118
1142  Sunrisers Hyderabad      Rising Pune Supergiants       557         137
1143  Sunrisers Hyderabad  Royal Challengers Bangalore       329         150
1144  Sunrisers Hyderabad  Royal Challengers Bangalore       373         161
1145  Sunrisers Hyderabad  Royal Challengers Bangalore       422         155
1146  Sunrisers Hyderabad  Royal Challengers Bangalore       444         161
1147  Sunrisers Hyderabad  Royal Challengers Bangalore       466         172
1148  Sunrisers Hyderabad  Royal Challengers Bangalore       509         135
1149  Sunrisers Hyderabad  Royal Challengers Bangalore       521         182
1150  Sunrisers Hyderabad  Royal Challengers Bangalore       544         194
1151  Sunrisers Hyderabad  Royal Challengers Bangalore       577         208

[1152 rows x 4 columns]

#### 5. Return a dataframe with the bowling details for bowlers for each match.
##### The resulting df will have 6866 rows and 6 columns and should look like the df given below.

In [9]:
d1 = {'batting_team': {0: 'Kolkata Knight Riders',
  1: 'Kolkata Knight Riders',
  2: 'Kolkata Knight Riders',
  3: 'Kolkata Knight Riders',
  4: 'Kolkata Knight Riders',
  5: 'Kolkata Knight Riders',
  6: 'Royal Challengers Bangalore',
  7: 'Royal Challengers Bangalore',
  8: 'Royal Challengers Bangalore',
  9: 'Royal Challengers Bangalore'},
 'bowler': {0: 'AA Noffke',
  1: 'CL White',
  2: 'JH Kallis',
  3: 'P Kumar',
  4: 'SB Joshi',
  5: 'Z Khan',
  6: 'AB Agarkar',
  7: 'AB Dinda',
  8: 'I Sharma',
  9: 'LR Shukla'},
 'bowling_team': {0: 'Royal Challengers Bangalore',
  1: 'Royal Challengers Bangalore',
  2: 'Royal Challengers Bangalore',
  3: 'Royal Challengers Bangalore',
  4: 'Royal Challengers Bangalore',
  5: 'Royal Challengers Bangalore',
  6: 'Kolkata Knight Riders',
  7: 'Kolkata Knight Riders',
  8: 'Kolkata Knight Riders',
  9: 'Kolkata Knight Riders'},
 'extra_runs': {0: 6, 1: 2, 2: 5, 3: 4, 4: 0, 5: 0, 6: 4, 7: 2, 8: 7, 9: 3},
 'match_id': {0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
 'total_runs': {0: 41,
  1: 24,
  2: 52,
  3: 41,
  4: 26,
  5: 38,
  6: 25,
  7: 9,
  8: 13,
  9: 12}}
df1 = pd.DataFrame(d1)
df1

,batting_team,bowler,bowling_team,extra_runs,match_id,total_runs
0,Kolkata Knight Riders,AA Noffke,Royal Challengers Bangalore,6,1,41
1,Kolkata Knight Riders,CL White,Royal Challengers Bangalore,2,1,24
2,Kolkata Knight Riders,JH Kallis,Royal Challengers Bangalore,5,1,52
3,Kolkata Knight Riders,P Kumar,Royal Challengers Bangalore,4,1,41
4,Kolkata Knight Riders,SB Joshi,Royal Challengers Bangalore,0,1,26
5,Kolkata Knight Riders,Z Khan,Royal Challengers Bangalore,0,1,38
6,Royal Challengers Bangalore,AB Agarkar,Kolkata Knight Riders,4,1,25
7,Royal Challengers Bangalore,AB Dinda,Kolkata Knight Riders,2,1,9
8,Royal Challengers Bangalore,I Sharma,Kolkata Knight Riders,7,1,13
9,Royal Challengers Bangalore,LR Shukla,Kolkata Knight Riders,3,1,12

In [10]:
bowling = deliveries.groupby(['batting_team','bowler','bowling_team', 'match_id'],as_index = False)['extra_runs','total_runs'].sum().sort_values(by='match_id',ascending='true')

In [11]:
bowling

,batting_team,bowler,bowling_team,match_id,extra_runs,total_runs
3668,Kolkata Knight Riders,SB Joshi,Royal Challengers Bangalore,1,0,26
3183,Kolkata Knight Riders,CL White,Royal Challengers Bangalore,1,2,24
6058,Royal Challengers Bangalore,LR Shukla,Kolkata Knight Riders,1,3,12
3092,Kolkata Knight Riders,AA Noffke,Royal Challengers Bangalore,1,6,41
3822,Kolkata Knight Riders,Z Khan,Royal Challengers Bangalore,1,0,38
3501,Kolkata Knight Riders,P Kumar,Royal Challengers Bangalore,1,4,41
6338,Royal Challengers Bangalore,SC Ganguly,Kolkata Knight Riders,1,3,23
3343,Kolkata Knight Riders,JH Kallis,Royal Challengers Bangalore,1,5,52
5722,Royal Challengers Bangalore,AB Agarkar,Kolkata Knight Riders,1,4,25
5727,Royal Challengers Bangalore,AB Dinda,Kolkata Knight Riders,1,2,9
5925,Royal Challengers Bangalore,I Sharma,Kolkata Knight Riders,1,7,13
103,Chennai Super Kings,B Lee,Kings XI Punjab,2,2,36
748,Chennai Super Kings,WA Mota,Kings XI Punjab,2,2,24
241,Chennai Super Kings,IK Pathan,Kings XI Punjab,2,0,47
2598,Kings XI Punjab,MS Gony,Chennai Super Kings,2,3,43
2549,Kings XI Punjab,M Muralitharan,Chennai Super Kings,2,4,35
311,Chennai Super Kings,JR Hopes,Kings XI Punjab,2,1,54
454,Chennai Super Kings,PP Chawla,Kings XI Punjab,2,0,19
603,Chennai Super Kings,S Sreesanth,Kings XI Punjab,2,1,35
2441,Kings XI Punjab,JDP Oram,Chennai Super Kings,2,0,37
2621,Kings XI Punjab,P Amarnath,Chennai Super Kings,2,3,45
2482,Kings XI Punjab,Joginder Sharma,Chennai Super Kings,2,1,47
315,Chennai Super Kings,K Goel,Kings XI Punjab,2,0,25
2023,Delhi Daredevils,YK Pathan,Rajasthan Royals,3,1,17
1914,Delhi Daredevils,SK Warne,Rajasthan Royals,3,0,16
5050,Rajasthan Royals,DL Vettori,Delhi Daredevils,3,0,35
1390,Delhi Daredevils,D Salunkhe,Rajasthan Royals,3,5,11
1906,Delhi Daredevils,SK Trivedi,Rajasthan Royals,3,3,32
5083,Rajasthan Royals,GD McGrath,Delhi Daredevils,3,1,21
1947,Delhi Daredevils,SR Watson,Rajasthan Royals,3,1,31
...,...,...,...,...,...,...
6623,Sunrisers Hyderabad,JO Holder,Kolkata Knight Riders,575,2,33
3170,Kolkata Knight Riders,Bipul Sharma,Sunrisers Hyderabad,575,2,18
6750,Sunrisers Hyderabad,R Sathish,Kolkata Knight Riders,575,0,9
3161,Kolkata Knight Riders,BCJ Cutting,Sunrisers Hyderabad,575,0,14
3480,Kolkata Knight Riders,Mustafizur Rahman,Sunrisers Hyderabad,575,2,30
3160,Kolkata Knight Riders,BB Sran,Sunrisers Hyderabad,575,4,33
2137,Gujarat Lions,TA Boult,Sunrisers Hyderabad,576,2,39
2068,Gujarat Lions,Bipul Sharma,Sunrisers Hyderabad,576,0,21
6563,Sunrisers Hyderabad,DS Kulkarni,Gujarat Lions,576,0,32
6786,Sunrisers Hyderabad,SK Raina,Gujarat Lions,576,0,15
6559,Sunrisers Hyderabad,DR Smith,Gujarat Lions,576,0,29
6709,Sunrisers Hyderabad,P Kumar,Gujarat Lions,576,2,33
2066,Gujarat Lions,BCJ Cutting,Sunrisers Hyderabad,576,0,20
2101,Gujarat Lions,MC Henriques,Sunrisers Hyderabad,576,0,27
6553,Sunrisers Hyderabad,DJ Bravo,Gujarat Lions,576,0,32
2062,Gujarat Lions,B Kumar,Sunrisers Hyderabad,576,2,27
6777,Sunrisers Hyderabad,S Kaushik,Gujarat Lions,576,0,22
2065,Gujarat Lions,BB Sran,Sunrisers Hyderabad,576,1,28
6544,Sunrisers Hyderabad,CJ Jordan,Royal Challengers Bangalore,577,8,47
6601,Sunrisers Hyderabad,Iqbal Abdulla,Royal Challengers Bangalore,577,0,10
6812,Sunrisers Hyderabad,SR Watson,Royal Challengers Bangalore,577,2,61
5799,Royal Challengers Bangalore,BB Sran,Sunrisers Hyderabad,577,2,41
6090,Royal Challengers Bangalore,MC Henriques,Sunrisers Hyderabad,577,0,40
5800,Royal Challengers Bangalore,BCJ Cutting,Sunrisers Hyderabad,577,1,35
5806,Royal Challengers Bangalore,Bipul Sharma,Sunrisers Hyderabad,577,0,17
6859,Sunrisers Hyderabad,YS Chahal,Royal Challengers Bangalore,577,1,36
5790,Royal Challengers Bangalore,B Kumar,Sunrisers Hyderabad,577,5,29
6143,Royal Challengers Bangalore,Mustafizur Rahman,Sunrisers Hyderabad,577,1,38
6536,Sunrisers Hyderabad,CH Gayle,Royal Challengers Bangalore,577,3,24
6773,Sunrisers Hyderabad,S Aravind,Royal Challengers Bangalore,577,0,30

#### 6. What is the highest and the lowest total score made, give the name of the batting team and runs scored in each case

In [12]:
deliveries.groupby(['match_id','batting_team','bowling_team']).total_runs.sum().reset_index().agg([max,min])

     match_id         batting_team         bowling_team  total_runs
max       577  Sunrisers Hyderabad  Sunrisers Hyderabad         263
min         1  Chennai Super Kings  Chennai Super Kings           2

#### 7. What is the most common way the players got out in the IPL? How many?

In [13]:
deliveries.groupby(['dismissal_kind']).count().reset_index().max().head(1)

dismissal_kind    stumped
dtype: object

#### 8. Who is the highest wicket-taker for CSK? How many wickets?

In [14]:
deliveries.groupby(['bowling_team', 'bowler']).dismissal_kind.count().loc[['Chennai Super Kings']].reset_index().max()

bowling_team      Chennai Super Kings
bowler                      VY Mahesh
dismissal_kind                     99
dtype: object

#### 9. Add a column called 'Howzthat' that has shows 'Yay' if the corresponding player_dismissed column has non NaN value and 'Nay' if player_dismissed is NaN. Hint: lookat np.where()

In [15]:
deliveries['Howzthat'] = np.where((deliveries['player_dismissed'].notnull()) , 'Yay', 'Nay')
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder,Howzthat
0,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,SC Ganguly,BB McCullum,P Kumar,0,...,1,0,0,0,1,1,NaN,NaN,NaN,Nay
1,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
2,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,1,1,NaN,NaN,NaN,Nay
3,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,4,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
4,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,5,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
5,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,6,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
6,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,7,BB McCullum,SC Ganguly,P Kumar,0,...,1,0,0,0,1,1,NaN,NaN,NaN,Nay
7,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,1,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
8,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,2,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,0,4,0,4,NaN,NaN,NaN,Nay
9,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,3,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,0,4,0,4,NaN,NaN,NaN,Nay
10,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,4,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,0,6,0,6,NaN,NaN,NaN,Nay
11,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,5,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,0,4,0,4,NaN,NaN,NaN,Nay
12,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,6,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
13,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,1,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
14,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,2,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
15,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,3,SC Ganguly,BB McCullum,P Kumar,0,...,1,0,0,0,1,1,NaN,NaN,NaN,Nay
16,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,4,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,4,0,4,NaN,NaN,NaN,Nay
17,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,5,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
18,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,6,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
19,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,1,BB McCullum,SC Ganguly,AA Noffke,0,...,0,0,0,0,5,5,NaN,NaN,NaN,Nay
20,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,2,BB McCullum,SC Ganguly,AA Noffke,0,...,0,0,0,6,0,6,NaN,NaN,NaN,Nay
21,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,3,BB McCullum,SC Ganguly,AA Noffke,0,...,1,0,0,0,1,1,NaN,NaN,NaN,Nay
22,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,4,SC Ganguly,BB McCullum,AA Noffke,0,...,0,0,0,4,0,4,NaN,NaN,NaN,Nay
23,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,5,SC Ganguly,BB McCullum,AA Noffke,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
24,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,6,SC Ganguly,BB McCullum,AA Noffke,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
25,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,7,BB McCullum,SC Ganguly,AA Noffke,0,...,0,0,0,6,0,6,NaN,NaN,NaN,Nay
26,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,1,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,0,4,0,4,NaN,NaN,NaN,Nay
27,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,2,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
28,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,3,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,4,0,4,NaN,NaN,NaN,Nay
29,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,4,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136568,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,1,KL Rahul,SR Watson,BCJ Cutting,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
136569,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,2,SR Watson,KL Rahul,BCJ Cutting,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
136570,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,3,KL Rahul,SR Watson,BCJ Cutting,0,...,0,0,0,0,0,0,KL Rahul,bowled,NaN,Yay
136571,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,4,Sachin Baby,SR Watson,BCJ Cutting,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
136572,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,5,Sachin Baby,SR Watson,BCJ Cutting,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
136573,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,6,SR Watson,Sachin Baby,BCJ Cutting,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
136574,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,1,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
136575,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,2,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,2,0,2,NaN,NaN,NaN,Nay
136576,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,3,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,0,SR Watson,caught,MC Henriques,Yay
136577,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,4,Sachin Baby,STR Binny,Mustafizur Rahman,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
136578,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,5,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,6,0,6,NaN,NaN,NaN,Nay
136579,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,6,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
136580,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,1,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
136581,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,2,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
136582,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,3,Sachin Baby,STR Binny,B Kumar,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
136583,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,4,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
136584,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,5,STR Binny,Sachin Baby,B Kumar,0,...,1,0,0,0,1,1,NaN,NaN,NaN,Nay
136585,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,6,Sachin Baby,STR Binny,B Kumar,0,...,0,0,0,4,0,4,NaN,NaN,NaN,Nay
136586,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,1,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,1,0,1,STR Binny,run out,DJ Hooda,Yay
136587,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,2,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,2,0,2,NaN,NaN,NaN,Nay
136588,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,3,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,0,NaN,NaN,NaN,Nay
136589,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,4,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,1,0,0,0,1,1,NaN,NaN,NaN,Nay
136590,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,5,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,2,0,2,NaN,NaN,NaN,Nay
136591,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,6,0,6,NaN,NaN,NaN,Nay
136592,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,1,CJ Jordan,Sachin Baby,B Kumar,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
136593,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,2,0,2,NaN,NaN,NaN,Nay
136594,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha,Yay
136595,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,1,0,0,0,1,1,NaN,NaN,NaN,Nay
136596,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,1,0,1,NaN,NaN,NaN,Nay
136597,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,4,0,4,NaN,NaN,NaN,Nay

#### 10. Add a column 'run_run' which checks total_runs column and say 
#### 'Duck' if total_runs is 0, 
#### 'come_on' if total_runs is 1 or 2,
#### 'cool' if total_runs is 3,
#### 'hit!' if total_runs is 4 or 6. 
##### Hint: you can write a function using nested if-else and apply that function to df.total_runs

In [16]:
def check_runs(total):
    if total == 0:
        return "Duck"
    elif ((total == 1) | (total == 2)):
          return "come_on"
    elif total == 3:
          return "cool"
    elif ((total == 4) | (total == 6)):
          return "cool"

deliveries['run_run'] = deliveries.total_runs.apply(check_runs)
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder,Howzthat,run_run
0,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,0,1,1,NaN,NaN,NaN,Nay,come_on
1,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
2,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,1,1,NaN,NaN,NaN,Nay,come_on
3,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,4,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
4,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,5,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
5,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,6,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
6,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,7,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,1,1,NaN,NaN,NaN,Nay,come_on
7,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,1,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
8,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,2,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,4,0,4,NaN,NaN,NaN,Nay,cool
9,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,3,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,4,0,4,NaN,NaN,NaN,Nay,cool
10,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,4,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,6,0,6,NaN,NaN,NaN,Nay,cool
11,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,5,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,4,0,4,NaN,NaN,NaN,Nay,cool
12,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,6,BB McCullum,SC Ganguly,Z Khan,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
13,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,1,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
14,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,2,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
15,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,3,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,0,1,1,NaN,NaN,NaN,Nay,come_on
16,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,4,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,4,0,4,NaN,NaN,NaN,Nay,cool
17,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,5,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
18,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,6,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
19,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,1,BB McCullum,SC Ganguly,AA Noffke,0,...,0,0,0,5,5,NaN,NaN,NaN,Nay,None
20,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,2,BB McCullum,SC Ganguly,AA Noffke,0,...,0,0,6,0,6,NaN,NaN,NaN,Nay,cool
21,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,3,BB McCullum,SC Ganguly,AA Noffke,0,...,0,0,0,1,1,NaN,NaN,NaN,Nay,come_on
22,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,4,SC Ganguly,BB McCullum,AA Noffke,0,...,0,0,4,0,4,NaN,NaN,NaN,Nay,cool
23,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,5,SC Ganguly,BB McCullum,AA Noffke,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
24,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,6,SC Ganguly,BB McCullum,AA Noffke,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
25,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,4,7,BB McCullum,SC Ganguly,AA Noffke,0,...,0,0,6,0,6,NaN,NaN,NaN,Nay,cool
26,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,1,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,4,0,4,NaN,NaN,NaN,Nay,cool
27,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,2,SC Ganguly,BB McCullum,P Kumar,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
28,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,3,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,4,0,4,NaN,NaN,NaN,Nay,cool
29,1,1,Kolkata Knight Riders,Royal Challengers Bangalore,5,4,BB McCullum,SC Ganguly,P Kumar,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136568,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,1,KL Rahul,SR Watson,BCJ Cutting,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
136569,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,2,SR Watson,KL Rahul,BCJ Cutting,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
136570,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,3,KL Rahul,SR Watson,BCJ Cutting,0,...,0,0,0,0,0,KL Rahul,bowled,NaN,Yay,Duck
136571,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,4,Sachin Baby,SR Watson,BCJ Cutting,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
136572,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,5,Sachin Baby,SR Watson,BCJ Cutting,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
136573,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,16,6,SR Watson,Sachin Baby,BCJ Cutting,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
136574,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,1,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
136575,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,2,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,2,0,2,NaN,NaN,NaN,Nay,come_on
136576,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,3,SR Watson,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,SR Watson,caught,MC Henriques,Yay,Duck
136577,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,4,Sachin Baby,STR Binny,Mustafizur Rahman,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
136578,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,5,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,6,0,6,NaN,NaN,NaN,Nay,cool
136579,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,6,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
136580,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,1,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
136581,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,2,STR Binny,Sachin Baby,B Kumar,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
136582,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,3,Sachin Baby,STR Binny,B Kumar,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
136583,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,4,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
136584,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,5,STR Binny,Sachin Baby,B Kumar,0,...,0,0,0,1,1,NaN,NaN,NaN,Nay,come_on
136585,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,18,6,Sachin Baby,STR Binny,B Kumar,0,...,0,0,4,0,4,NaN,NaN,NaN,Nay,cool
136586,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,1,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,1,0,1,STR Binny,run out,DJ Hooda,Yay,come_on
136587,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,2,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,0,2,0,2,NaN,NaN,NaN,Nay,come_on
136588,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,3,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,0,NaN,NaN,NaN,Nay,Duck
136589,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,4,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,1,1,NaN,NaN,NaN,Nay,come_on
136590,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,5,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,2,0,2,NaN,NaN,NaN,Nay,come_on
136591,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,6,0,6,NaN,NaN,NaN,Nay,cool
136592,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,1,CJ Jordan,Sachin Baby,B Kumar,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
136593,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,2,0,2,NaN,NaN,NaN,Nay,come_on
136594,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,CJ Jordan,run out,NV Ojha,Yay,Duck
136595,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,1,1,NaN,NaN,NaN,Nay,come_on
136596,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,1,0,1,NaN,NaN,NaN,Nay,come_on
136597,577,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,4,0,4,NaN,NaN,NaN,Nay,cool